#!/bin/bash

# first
# This file looks through all the files in the current
# directory for the string POSIX, and then prints the name of
# those files to the standard output.

for file in *
do
  if grep -q main $file
#参数-q表示quiet,不显示内容到窗口  
  then
    echo $file 
  fi
done

exit 0
