#!/bin/bash

#trap command signal
#信号名称为SIGINT，省略SIG
trap "rm -f my_tmp_file_$$" INT
echo creating file my_tmp_file_$$
date > my_tmp_file_$$

echo "Press interrupt (Ctrl-C) to interrupt...."
while [ -f my_tmp_file_$$ ]; do
    echo File exists
    sleep 1
done
echo The file no longer exists

trap INT
#command为空，默认处理该信号，终止程序
#command为-，或者为""，忽略该信号

echo creating file my_tmp_file_$$
date > my_tmp_file_$$

echo "Press interrupt (Ctrl-C) to interrupt...."
while [ -f my_tmp_file_$$ ]; do
    echo File exists
    sleep 1
done

echo We never get here

exit 0

