#!/bin/bash
#变量
#======================Part1=====================
echo ======================Part1=====================
val=Hello
echo $val

val="Yes Dear"
echo $val

val=7+5
echo $val

echo Enter some text
read val
echo $val

#1.所有变量都被看做是字符串
#2.如果字符串中有空格，必须使用双引号
#3.等号两边不能有空格
#4.read命令将用户的输入赋值给变量
#======================Part2=====================
echo ======================Part2=====================
myvar="Hi there"

echo $myvar
echo "$myvar"
echo '$myvar'
echo \$myvar

echo Enter some text
read myvar

echo '$myvar' now equals $myvar
#1.在变量前加$显示变量内容
#2.使用双引号效果一样
#3.使用单引号不显示变量内容
#4.使用\反斜杠不显示变量内容
exit 0
